name: Update cn Rule

on:
  schedule:
    - cron: "50 0,8,16 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq wget tar

    - name: Download base JSON
      run: |
        curl -o upstream_cn.json https://raw.githubusercontent.com/DustinWin/ruleset_geodata/sing-box-ruleset/cn.json

    - name: Process local rules in JSON
      run: |
        local_rules=$(jq -R -s -c 'split("\n")[:-1]' cn.txt)

        jq --argjson new_rules "$local_rules" '
          .rules[0].domain_suffix += $new_rules |
          .rules[0].domain_suffix = (if .rules[0].domain_suffix | length > 0 then .rules[0].domain_suffix | unique | sort else .rules[0].domain_suffix end)
        ' upstream_cn.json > cn.json

        jq . cn.json

    - name: Setup sing-box
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert JSON to SRS
      run: |
        sing-box rule-set compile --output cn.srs cn.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cn.json cn.srs
        git commit -m "Update cn rules" || echo "No changes to commit"
        git push
